export const AFRICAN_CURRENCIES = [
  { code: 'XAF', name: 'Franc CFA BEAC (XAF)' },
  { code: 'XOF', name: 'Franc CFA BCEAO (XOF)' },
  { code: 'NGN', name: 'Naira (NGN)' },
  { code: 'ZAR', name: 'Rand (ZAR)' },
  { code: 'EGP', name: 'Egyptian Pound (EGP)' },
  { code: 'KES', name: 'Kenyan Shilling (KES)' },
  { code: 'GHS', name: 'Ghanaian Cedi (GHS)' },
  { code: 'MAD', name: 'Moroccan Dirham (MAD)' },
  { code: 'DZD', name: 'Algerian Dinar (DZD)' },
  { code: 'TND', name: 'Tunisian Dinar (TND)' },
  { code: 'ETB', name: 'Ethiopian Birr (ETB)' },
  { code: 'UGX', name: 'Ugandan Shilling (UGX)' },
  { code: 'RWF', name: 'Rwandan Franc (RWF)' },
  { code: 'BWP', name: 'Botswana Pula (BWP)' },
  { code: 'MUR', name: 'Mauritian Rupee (MUR)' },
  { code: 'SCR', name: 'Seychellois Rupee (SCR)' },
  { code: 'MWK', name: 'Malawian Kwacha (MWK)' },
  { code: 'ZMW', name: 'Zambian Kwacha (ZMW)' },
  { code: 'AOA', name: 'Angolan Kwanza (AOA)' },
  { code: 'MZN', name: 'Mozambican Metical (MZN)' },
  { code: 'NAD', name: 'Namibian Dollar (NAD)' },
  { code: 'SZL', name: 'Swazi Lilangeni (SZL)' },
  { code: 'LSL', name: 'Lesotho Loti (LSL)' },
  { code: 'GMD', name: 'Gambian Dalasi (GMD)' },
  { code: 'SLL', name: 'Sierra Leonean Leone (SLL)' },
  { code: 'LRD', name: 'Liberian Dollar (LRD)' },
  { code: 'GNF', name: 'Guinean Franc (GNF)' },
  { code: 'CVE', name: 'Cape Verdean Escudo (CVE)' },
  { code: 'STD', name: 'São Tomé and Príncipe Dobra (STD)' },
  { code: 'KMF', name: 'Comorian Franc (KMF)' },
  { code: 'DJF', name: 'Djiboutian Franc (DJF)' },
  { code: 'ERN', name: 'Eritrean Nakfa (ERN)' },
  { code: 'SOS', name: 'Somali Shilling (SOS)' },
  { code: 'SSP', name: 'South Sudanese Pound (SSP)' },
  { code: 'SDG', name: 'Sudanese Pound (SDG)' },
  { code: 'LYD', name: 'Libyan Dinar (LYD)' },
  { code: 'MRO', name: 'Mauritanian Ouguiya (MRO)' },
  { code: 'EUR', name: 'Euro (EUR)' },
  { code: 'USD', name: 'US Dollar (USD)' },
  { code: 'GBP', name: 'British Pound (GBP)' },
];
